[package]
name = "web-worker-fun"
version = "0.1.0"
authors = ["Logan Keenan <email@email.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
basic-http-server = "0.8.1"
